//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace School_10.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Klassi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Klassi()
        {
            this.Uchenikis = new HashSet<Ucheniki>();
            this.Urokis = new HashSet<Uroki>();
        }
    
        public int ID_Klassa { get; set; }
        public Nullable<System.DateTime> god_nach { get; set; }
        public Nullable<System.DateTime> god_Obuch { get; set; }
        public string Bukva { get; set; }
        public string Name { get; set; }
        public int Rukovoditel_ID { get; set; }
    
        public virtual Teacher Teacher { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ucheniki> Uchenikis { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Uroki> Urokis { get; set; }
    }
}
