//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace School_10.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ucheniki
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ucheniki()
        {
            this.Uroki_Ucheniki = new HashSet<Uroki_Ucheniki>();
        }
    
        public int Uchenik_ID { get; set; }
        public int Klass_ID { get; set; }
        public string Familia { get; set; }
        public string Name { get; set; }
        public string Otchestvo { get; set; }
        public Nullable<System.DateTime> Date_rojden { get; set; }
        public Nullable<System.DateTime> Date_Postuplen { get; set; }
        public string Primechania { get; set; }
        public string Roditeli { get; set; }
        public Nullable<int> User_ID { get; set; }
    
        public virtual Klassi Klassi { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Uroki_Ucheniki> Uroki_Ucheniki { get; set; }
    }
}
